### PR TITLE
add timeout to dumpAndReload

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Review by DvirDukhan — APPROVED** [review]

**Comment by MeirShpilraien** [comment]
I believe this parameter is misleading because its not a timeout on the dump + restore, its a timeout on waiting for cluster be available on cluster env.

**Comment by gkorland** [comment]
@MeirShpilraien what do you suggest instead?

**Comment by DvirDukhan** [comment]
@gkorland maybe try renaming it to `env_cluster_timeout`?

**Comment by MeirShpilraien** [comment]
I am not sure what is the original that led adding this?

**Comment by DvirDukhan** [comment]
our CI fails on cluster tests with valgrind on this timeout

**Pull request merged**
